[package]
name = "embedded-audio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.16.0"
rust-embed = "6.4.1"

[[example]]
name = "main"
path = "src/main.rs"

